# Generated by Django 5.0.6 on 2026-05-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ai_provider_preference',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('groq', 'Groq')], default='groq', max_length=20),
        ),
    ]
