# Generated by Django 5.0.6 on 2026-05-14 16:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('summary', 'Generate Summary'), ('action_items', 'Extract Action Items'), ('suggest_title', 'Suggest Title')], db_index=True, max_length=20)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini')], default='gemini', max_length=10)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ai_usage_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
