# Generated by Django 5.0.6 on 2026-06-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_features', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('groq', 'Groq')], default='gemini', max_length=10),
        ),
    ]
