# Generated by Django 5.0.6 on 2026-05-14 16:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='Untitled Note', max_length=255)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], db_index=True, default='private', max_length=10)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_action_items', models.JSONField(blank=True, default=list)),
                ('ai_suggested_title', models.CharField(blank=True, max_length=255)),
                ('share_id', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='notes', to='notes.tag')),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'name'], name='tags_user_id_eb4e0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'status'], name='notes_user_id_90ed5e_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'updated_at'], name='notes_user_id_3ab1c3_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'visibility'], name='notes_user_id_e20955_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['share_id'], name='notes_share_i_a4d5fa_idx'),
        ),
    ]
